[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/img/raw/*"
  to = "/.netlify/functions/serve-image"
  status = 200

[[redirects]]
  from = "/img/*"
  to = "/.netlify/functions/serve-image"
  status = 200
